# Generated by Django 5.1.4 on 2024-12-11 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_user_groups_user_user_permissions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organization",
            old_name="local_level",
            new_name="province",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="local_level",
            new_name="province",
        ),
    ]
