# Generated by Django 5.1.4 on 2024-12-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_rename_local_level_organization_province_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("user", "User"), ("organization", "Organization")],
                default="user",
                max_length=15,
            ),
        ),
    ]
